### ISSUE TITLE
Format CSS file

### ISSUE THREAD

**Issue by rudnitskih** [Ultimo2905/Elena-landing-Pages#3]

**Comment by Ultimo2905** [comment]
Я не знаю як це робити в саблаймі

**Comment by rudnitskih** [comment]
Це не аргумент!!! Не знайдешь як зробити автоматично - слідкуй і зроби руками

**Comment by Ultimo2905** [comment]
ok use https://www.cleancss.com/css-beautify/ CSS Formatter

**Comment by rudnitskih** [comment]
it is bad approach to use external tools for it - please ask me this question on next lection

**Comment by Ultimo2905** [comment]
ок
