### ISSUE TITLE
Don't change font-weight on hover 

### ISSUE THREAD

**Issue by rudnitskih** [Ultimo2905/Elena-landing-Pages#4]
Remove all effects on hover and change only or opacity, or background color.

https://github.com/Ultimo2905/DZ-15.10.2018/blob/master/css/style.css#L397

**Comment by Ultimo2905** [comment]
#4 Ок виправлю.
Але знайте ви не даєте розкритися творчі натурі :-)

**Comment by Ultimo2905** [comment]
button:hover прибрав
