### ISSUE TITLE
Wrong divider color

### ISSUE THREAD

**Issue by rudnitskih** [Ultimo2905/Elena-landing-Pages#9]
![image](https://user-images.githubusercontent.com/8848858/46919203-7196c700-cfe4-11e8-8ffd-d437e0ec90b9.png)

**Comment by rudnitskih** [comment]
![image](https://user-images.githubusercontent.com/8848858/46919213-b3277200-cfe4-11e8-9302-30d1428ba83c.png)

**Comment by Ultimo2905** [comment]
В коді все правильно. Там не колір, там  opacity: 0.8;, але чомусь нит хаб не відображає це 
![image](https://user-images.githubusercontent.com/43437388/46940147-b10af500-d070-11e8-854c-91806c0a9591.png)

**Comment by Ultimo2905** [comment]
Це відкрито з комп'ютера
